# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 977238a1fb4168b988560de4d3cbe8700c3bbc68d2eae33d0883b48b4edda4fd8f6acc18a16aa5d73fbfc7a350415cbad515aba3dd0a20472c72dcb252538a1f

test:
  secret_key_base: 2cf105dff538edf0c1ca138555db5b24316066094aa6125ad8e0a2d5547f3c87a08b61e4e1e5ce643fee5b990993c3e2eec6f0db1aaf260935be69234e0d5597

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
